services:
  - type: web
    name: django1
    env: python
    pythonVersion: "3.10"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn Django1.wsgi:application --bind 0.0.0.0:$PORT"